name: chatgpt-code-reviewer
run-name: chatgpt-code-reviewer
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  chatgpt-code-reviewer:
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'renovate/')"
    steps:
      - name: ChatGPT Review
        uses: magnificode-ltd/chatgpt-code-reviewer@v0.0.8
        #        with:
        #          model: gpt-3.5-turbo
        #          max_tokens: 65536
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.openai_api_key }}
